require(adehabitatLT) # help(package='adehabitat') # help.search('angle',package='adehabitat')
require(maps)       # for map.where
require(mapdata)    # for worldHires
require(sp)
require(maptools)
require(mgcv)
library(ape)
library(ncf)
library(ncdf4)
library(spdep)
require(ROCR)
require(dismo)
require(gbm)
require(tidyverse)
require(stringr)
library(spdep)
library(caret)
library(mlbench)
library(dismo)
library(gbm)
#library(lubridate)
library(qmap)
#library(dplyr)
library(Hmisc)
require(ggplot2)
require(ggmap)
require(lubridate)
require(RColorBrewer)
require(viridis)
require(gridExtra)
require(scales)
require(rnaturalearth)
require(rgeos)
library(glue)
library(reshape2)
library(mgcViz)
